### ISSUE TITLE
Input Upper Case characters = error

### ISSUE THREAD

**Issue by joelabair** [visionmedia/bytes.js#14]
bash >node
> bytes = require('bytes')
[Function]
> bytes('5MB')
TypeError: Cannot read property '1' of null
    at module.exports (./node_modules/bytes/index.js:13:27)
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.EventEmitter.emit (events.js:98:17)
> bytes('5mb')
5242880

**Comment by theofidry** [comment]
+1

**Comment by theofidry** [comment]
Done in https://github.com/theofidry/bytes.js.

**Comment by rhys-vdw** [comment]
I'm confused by this, isn't `Mb` megabits, whereas `MB` is megabytes? It seems the API of this module is kind of broken in general. Shouldn't `mb` be an error, as lower-case `m` has no meaning in this context?

**Comment by tj** [comment]
@rhys-vdw technically `MiB` no? This module was never really intended to get that specific, but I'd +1 a new major-level release that fixes things up. Personally I'd still prefer `--limit 5mb` over `--limit 5MiB` etc but hey

**Comment by theofidry** [comment]
According to [Wikipedia](http://en.m.wikipedia.org/wiki/Megabyte), it's MB.

As for using 'mb' as an input, I would be more the kind to be fault tolerant and interpret it as 'MB' instead of throwing an error.

But that raises the point of what will happen if you pass a value not understood (like '1my'). I don't remember of it uses bytes by default or return null.

**Comment by theofidry** [comment]
It does return null if there is an error*

**Comment by rhys-vdw** [comment]
I think @tj is correct in that the units that this library deals with are multiples of 1024, so technically 'mb' is interpreted as 'mibibytes'. However, in practise I never hear anyone using that term. I think I'd refer to mibibytes as 'megabytes'.

If it's interesting, the reason I suggested this was that I wanted to store the string in a config file, and also forward the error to the user. So:

```JavaScript
maxFileSize = config.get('maxFileSize');
if (file.size > bytes(maxFileSize)) {
  throw new Error('File exceeds maximum size of ' + maxFileSize);
}
```

But I don't want my error message (or config) to have the incorrect units. Obviously there are numerous workarounds for this (simplest being to change cases contextually).

I see now that this is really a pretty simple module with limited use cases. Unless you want to expand to handling conversion between different units (bytes, bits, mibibytes, megabytes) @theofidry's [solution](https://github.com/theofidry/bytes.js/blob/master/lib/byte-parse.js#L30) is probably most appropriate.

**Comment by tj** [comment]
I wouldn't mind support for bits/bytes since network config is typical in bits, but I'd definitely worry about people misconfiguring with different units
