### ISSUE TITLE
Nitpicking

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [visionmedia/bytes.js#18]
1 mb = 0.001 bits
1 Mb = 1'000'000 bits
1 mB = 0.001 bytes
1 MB = 1'000'000 bytes
1 MiB = 1'048'576 bytes

I'll go away now :smiley:

**Comment by theofidry** [comment]
Solved in https://github.com/theofidry/bytes.js.

**Comment by dougwilson** [comment]
Since @theofidry 's fork was merged, I believe, I'm closing this issue.
