### ISSUE TITLE
option to specify fixed decimal places

### ISSUE THREAD

**Issue by DonutEspresso** [visionmedia/bytes.js#25]
Would be nice to allow an option to specify a fixed number of decimal places. Something like:

```js
bytes(1000, { places: 2 });
// '1000.00B'
```

**Comment by dougwilson** [comment]
Hi @DonutEspresso , some PRs have been provided and just merged that will solve your use-case! Shortly version 2.2.0 will be published to npm and your example above will become the following:
```
$ node -pe 'require("bytes")(1000, {fixedDecimals: true})'
1000.00B
```

**Comment by DonutEspresso** [comment]
Thanks @dougwilson!
