### ISSUE TITLE
Browser Support/Inconsistencies

### ISSUE THREAD

**Issue by justinmc** [visionmedia/bytes.js#34]
I always get 2 decimal places when using this in the browser, the `decimalPlaces` option is ignored.  For example, in the browser:

    bytes(123123123, {decimalPlaces: 0}); //"117.42mb"

In Node, this correctly returns '117MB'.  Note also the difference in capitalization.

**Comment by dougwilson** [comment]
Are you sure you are running the same library in the browser and in Node.js? Can you paste the output of `bytes.toString()` when run in your browser? I just tried this module in the latest Firefox and Chrome and got `117MB` as expected.

**Comment by dougwilson** [comment]
Looking more, I see your issue: you are using a different version of this module in the browser than you are in Node.js. Version 1.0.0 and lower returns "mb" lowercase like you are seeing and doesn't support options like `decimalPlaces`, so it's just ignored. You need to use version 2.2.0 or higher to get the behavior you are expecting.

**Comment by justinmc** [comment]
On trying it again I do see the correct behavior in both places.  I must have been using the old version in the browser somehow.  Thanks for taking a look!

**Comment by dougwilson** [comment]
No problem
