### ISSUE TITLE
Is bytes.js available on a CDN somewhere?

### ISSUE THREAD

**Issue by hairyhenderson** [visionmedia/bytes.js#37]
I'd like to use bytes.js in a client-side, but all of my other dependencies are loaded from CDNs (like jsdelivr.com or cdnjs.com). I've not found it on any of the usual suspect CDNs -- is this available somewhere else, or could it be made available?

Thanks!

**Comment by tj** [comment]
I don't think it is, unless someone else added it (or if those services pull from repos, no clue)

**Comment by hairyhenderson** [comment]
Thanks @tj - I've requested it from cdnjs: https://github.com/cdnjs/cdnjs/issues/8560 

I'll see about requesting it from jsdelivr too...

**Comment by hairyhenderson** [comment]
jsdelivr PR: https://github.com/jsdelivr/jsdelivr/pull/12823

**Comment by megawac** [comment]
Replied on the jsdelivr thread, but auto updating will not work as there isn't a browser compatible file in the repo. If someone wants to compile a browser compatible version we'd accept it.

**Comment by pvnr0082t** [comment]
Hi, I'm a member of [cdnjs](https://www.github.com/cdnjs/cdnjs). Does `bytes.js` work in browsers? If not, is it possible to compile a browser compatible version? Thank you. 

https://github.com/cdnjs/cdnjs/pull/8642

**Comment by dougwilson** [comment]
Hi @pvnr0082t, I guess this module could work in the browser, but there is currently no browser build of the module nor do we test that it functions (or any given PR functions) in a browser, only in the Node.js environment.

**Comment by dougwilson** [comment]
I'm going to close this, because I'm not really interested in putting this on a CDN, but there is no reason why the community cannot do this, if it is desired. I would assume the basic is that you setup some process that will run this module through something like browserify and put that resulting file on a CDN.

**Comment by hairyhenderson** [comment]
👍
