### ISSUE TITLE
Discrepancy with 10x names

### ISSUE THREAD

**Issue by captDaylight** [visionmedia/bytes.js#49]
instead of in the Readme:

- b for bytes
- kb for kilobytes
- mb for megabytes
- gb for gigabytes
- tb for terabytes

shouldn't it be the following since this converts the binary? 

- b for bytes
- kb for kibibyte
- mb for mebibyte
- gb for gibibyte
- tb for tebibyte

<img width="357" alt="screen shot 2018-10-08 at 4 58 45 pm" src="https://user-images.githubusercontent.com/700617/46633392-87574880-cb1b-11e8-940a-7873b806cf51.png">

([source](https://en.wikipedia.org/wiki/Kibibyte))

**Comment by dougwilson** [comment]
#26
