### ISSUE TITLE
Thousands separator doesn't respect decimal points

### ISSUE THREAD

**Issue by rognales** [visionmedia/bytes.js#51]
This is my sample code

````js
var bytes = require('bytes');
var options = {thousandsSeparator: ',', decimalPlaces: 4, unit: 'GB', fixedDecimals:false, unitSeparator: ' '}
bytes(10241456, options);
````

Here's the output 
````js
"10,001.4,219 KB"
````

My expectation was
````js
"10,001.4219 KB"
````

**Comment by rognales** [comment]
Pardon me if this is due to locale setting as i cant find any

**Comment by dougwilson** [comment]
It certainly seems like a bug to me :)

**Comment by rognales** [comment]
3.1.1 fixes this!

Thanks for your great effort.

**Comment by dougwilson** [comment]
No problem @rognales . And sorry for letting this sit for so long. Going through and working though my huge backlog little bits at a time and happy to hear back that it helped :)
