### ISSUE TITLE
MB and KB issue 

### ISSUE THREAD

**Issue by sai1139** [visionmedia/bytes.js#52]
i have facing issue with mb and kb. i have written a if else /Switch, based on it converting the values.
But it was working as reverse way if condition is (mb) bytes convertor returning the kb values or else (KB)  bytes convertor returning the mb and there was no issue with gb;
please check below code:
if(mb)
bytes(`${value}mb`);
else
bytes(`${value}kb`);

**Comment by dougwilson** [comment]
Hello! I'm not clear on what the issue is.
