### ISSUE TITLE
Multiple converter

### ISSUE THREAD

**Issue by sai1139** [visionmedia/bytes.js#55]
## Feature Request
Get multiple converter values like  GB,MB,KB ,Based on value
Example:

var bytes = require("bytes")
bytes(1073741824 )
Return value:->1GB

Expected  value : 1GB, 1024MB,1048576 KB.

**Comment by dougwilson** [comment]
Duplicate of #19 effectively, as that feature would allow you to get all the levels you want for a specific value.

**Comment by sai1139** [comment]
I have one use case like
User having 60GB
-> 60 GB,0 MB,0KB
After he consumed 1mb
->59GB,1MB,0KB

This use case also will come into same or different?

**Comment by dougwilson** [comment]
Oh, I think I get what you are saying. That does seem different from the first example you originally provided.

**Comment by sai1139** [comment]
Yes

**Comment by sai1139** [comment]
@dougwilson you will open as new issue ?

**Comment by sai1139** [comment]
> Oh, I think I get what you are saying. That does seem different from the first example you originally provided.
for above usecase i opening new request
