### ISSUE TITLE
Feature Request: ES Module Export

### ISSUE THREAD

**Issue by arihantverma** [visionmedia/bytes.js#64]
Hello! 🌻

Since this module works perfectly fine in browsers as well, would it be useful to provide a ES Module and/or UMD version of the package as well? If yes, we could discuss as to how to achieve it and I could raise PR likewise.

**Comment by dougwilson** [comment]
Hello, and thank you for the offer. I am not really interested in supporting those environments, so if transforming using something like webpack is not an option, you are always welcome to publish a fork or similar that targets those environments :)
